### ISSUE TITLE
after installing the module stops working

### ISSUE THREAD

**Issue by kumarbikash411** [jasonujmaalvis/magento2-twitter#2]
after installin the module, i am facing problem as backend not working, but when i make changes to menu.xml 's parent id to JasonAlvis_Twitter::admin  , it works but not properly please suggest

**Comment by jasonujmaalvis** [comment]
Hello,

The parent id is set to `JasonAlvis_Core::admin` which is a dependency module. It sounds like you haven't used composer to install as it should have installed this dependency at the same time or the core module hasn't been enabled.

```
php bin/magento module:enable JasonAlvis_Core
php bin/magento module:enable JasonAlvis_Twitter
```

You can find the Core module [here](https://github.com/jasonalvis/magento2-core). It's just a simple wrapper to contain all my modules under 1 menu item in the admin area.

Hope this helps!

Thanks.
