### ISSUE TITLE
frontend error after the Manual installation of the module.

### ISSUE THREAD

**Issue by kumarbikash411** [jasonujmaalvis/magento2-twitter#3]
i was doing the manul installation by downloading the module 
1.downloaded the module core and module_twitter both also downloaded the abramh folder and put it into vendor folder but after that i am getting this kind of error..

Fatal error: Uncaught Error: Class 'Abraham\TwitterOAuth\TwitterOAuth' not found in /opt/lampp/htdocs/HN/app/code/Dotsquares/Twitter/Helper/Data.php:379 Stack trace: #0 /opt/lampp/htdocs/HN/app/code/Dotsquares/Twitter/Helper/Data.php(483): Dotsquares\Twitter\Helper\Data->twitterDevAuth() #1 /opt/lampp/htdocs/HN/app/code/Dotsquares/Twitter/Block/Tweets.php(148): Dotsquares\Twitter\Helper\Data->getLatestTweets('1') #2 [internal function]: Dotsquares\Twitter\Block\Tweets->getLatestTweets() #3 /opt/lampp/htdocs/HN/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array) #4 /opt/lampp/htdocs/HN/app/code/Dotsquares/Twitter/view/frontend/templates/tweets.phtml(20): Magento\Framework\View\TemplateEngine\Php->__call('getLatestTweets', Array) #5 /opt/lampp/htdocs/HN/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/opt/lampp/htdo...') #6 /opt/lampp/htdocs/HN/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Dotsquar in /opt/lampp/htdocs/HN/app/code/Dotsquares/Twitter/Helper/Data.php on line 379

**Comment by jasonujmaalvis** [comment]
Have you tried the compilation tasks:

```
php bin/magento setup:upgrade
php bin/magento setup:di:compile
```
